In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("ecommerce_sales_analytics_5000.csv",parse_dates=["order_date"])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

In [7]:
# Map() - label high-value orders
df["payment_type"]=df["payment_method"].map({
    "Card":"Digital",
    "Wallet":"Digital",
    "COD":"Cash"
})
# Explanation:Each value is mapped individually -> fast & simple

In [8]:
df["payment_type"].unique()

array(['Digital', 'Cash'], dtype=object)

In [9]:
df[["payment_method","payment_type"]].head()

  payment_method payment_type
0         Wallet      Digital
1           Card      Digital
2            COD         Cash
3         Wallet      Digital
4         Wallet      Digital

In [10]:
df.groupby("payment_type").size()

payment_type
Cash       1774
Digital    3226
dtype: int64

In [11]:
# Apply() - Create revenue category

def revenue_category(row):
    if row["revenue"] > 500:
        return "High"
    elif row["revenue"] >= 200:
        return "Medium"
    else:
        return "Low"

df["revenue_category"]=df.apply(revenue_category,axis=1)
#why apply ? Decision depends on multiple column

In [12]:
df["revenue_category"].value_counts()

revenue_category
High      3252
Medium    1098
Low        650
Name: count, dtype: int64

In [13]:
df[["revenue","revenue_category"]].sample(10)

      revenue revenue_category
3278  1225.18             High
1221  1417.09             High
3828  1486.53             High
4349   716.18             High
3397   304.12           Medium
1953   578.84             High
4167  2214.40             High
2445   590.54             High
4034   133.66              Low
2897   442.87           Medium

In [14]:
# pipe() - method chaining
def add_profit(data):
    data["profit"]=data["revenue"] * 0.20
    return data
def add_net_revenue(data):
    data["net_revenue"]=data["revenue"] - data["profit"]
    return data

df=(
    df 
    .pipe(add_profit)
    .pipe(add_net_revenue)
)

In [ ]:
df[["revenue",]]