In [1]:
import pandas as pd

In [2]:
## Series and Dataframe

In [4]:
pd_1=pd.Series([1,2,3,4,5])
print(pd_1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
data={
    "Name":["Ali","Ahmed","Sara"],
    "Class":[4,5,6],
    "Age":[18,19,34]
}
pd_2=pd.DataFrame(data)
pd_2

    Name  Class  Age
0    Ali      4   18
1  Ahmed      5   19
2   Sara      6   34

In [6]:
pd_2.head()

    Name  Class  Age
0    Ali      4   18
1  Ahmed      5   19
2   Sara      6   34

In [7]:
pd_2.tail()

    Name  Class  Age
0    Ali      4   18
1  Ahmed      5   19
2   Sara      6   34

In [9]:
pd_2.shape

(3, 3)

In [10]:
pd_2.columns

Index(['Name', 'Class', 'Age'], dtype='object')

In [11]:
pd_2.dtypes

Name     object
Class     int64
Age       int64
dtype: object

In [12]:
pd_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Class   3 non-null      int64
 2   Age     3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [13]:
pd_2.describe()

       Class        Age
count    3.0   3.000000
mean     5.0  23.666667
std      1.0   8.962886
min      4.0  18.000000
25%      4.5  18.500000
50%      5.0  19.000000
75%      5.5  26.500000
max      6.0  34.000000

In [14]:
### Task

data={
    "Name":["Ali","Ahmed","Sara","Farhan","Raza"],
    "Age":[20,21,19,22,20],
    "Marks":[85,72,91,68,88]
}
df=pd.DataFrame(data)
print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)

df.info()
print(df.describe())

     Name  Age  Marks
0     Ali   20     85
1   Ahmed   21     72
2    Sara   19     91
3  Farhan   22     68
4    Raza   20     88
(5, 3)
Index(['Name', 'Age', 'Marks'], dtype='object')
Name     object
Age       int64
Marks     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
             Age     Marks
count   5.000000   5.00000
mean   20.400000  80.80000
std     1.140175  10.18332
min    19.000000  68.00000
25%    20.000000  72.00000
50%    20.000000  85.00000
75%    21.000000  88.00000
max    22.000000  91.00000